- 02_bash/hwdetect/hwdetect.sh
In hwdetect.sh implemented notification messages about usb devices connection/disconnection
> TASK2: develop hwdetect.sh

- 01_git/scissors/Makefile
- 01_git/scissors/main.cpp
- 02_bash/hwdetect/hwdetect.sh
Task 1: scissors
Task 2: hwdetect
> Andrey.berdnik

- 01_git/rps/.clang-format
- 01_git/rps/.gitignore
- 01_git/rps/CMakeLists.txt
- 01_git/rps/src/datatypes/constants.h
- 01_git/rps/src/datatypes/enums.h
- 01_git/rps/src/driver/player_move.cpp
- 01_git/rps/src/driver/player_move.h
- 01_git/rps/src/main.cpp
- 01_git/rps/src/ui/user_interface.h
- 02_bash/hwdetect.sh
- 03_module/Makefile
- 03_module/README.md
- 03_module/custom_printk.c
- 03_module/custom_printk.ko.log
- 04_basic_struct/README.md
Add the implementation for the first two tasks.
> Add task.01, task.02, task.03 implementation

- 01_git/makefile
- 01_git/scissors.c
- 01_git/scissors.h
Add initial revision of homework task
> 01_git: Create rock-paper-scissors game

- 02_bash/hwdetect.sh
Add initial revision of script
> 02_bash: Create script witch detects connected hardware

- 03_module/Makefile
- 03_module/dump.txt
- 03_module/prmmod.c
Add first revision of kernel module with parameters
Module outputs:
- A sum of parameters upon driver load
- A substraction of parameters upon unload
> 03_module: Create simple loadable kernel module with parameters

- 03_module/README.md
- 04_basic_struct/README.md
No course-related changes added. Needed to reduce noise in TASK3 pull request.
> GENERAL: Update working branch from origin/main.

- 01_git/scissors/scissors.sh
Implemented Scissors game on Bash language with md5 information generation for the computer player.
> Task1: Implemented Scissors game

- 01_git/scissors/CMakeLists.txt
- 01_git/scissors/Makefile
- 01_git/scissors/game_common.h
- 01_git/scissors/main.c
- 03_module/README.md
- 03_module/solution/Makefile
- 03_module/solution/buildroot_building.md
- 03_module/solution/module_on_qemu.md
- 03_module/solution/qemu_start_log.txt
- 03_module/solution/start_qemu.sh
- 03_module/solution/sum_module.c
- 04_basic_struct/Makefile
- 04_basic_struct/README.md
- 04_basic_struct/basic_struct_module.c
- 04_basic_struct/test_mod.sh
Implemented assignments 01/03/04
> Assignment 01_git:game/03_module/04_module

- 03_module/README.md
- 04_basic_struct/Makefile
- 04_basic_struct/README.md
- 04_basic_struct/dump.txt
- 04_basic_struct/recv_msg.c
On read form attribute “list” show content of the objects linked list.
On write to attribute “list” add new string to the objects linked list.
During rmmod clear all received strings and free all resources.
> 04 task: Create module with linked_list structure 

- 01_git/scissors/.gitignore
- 01_git/scissors/Makefile
- 01_git/scissors/scissors.c
Implemented scissors game according task-01.
> TASK1: Implement scissors game

- 01_git/scissors/README.md
- 01_git/scissors/my_random.sh
- 01_git/scissors/rock-paper-scissors.sh
- scissors/README.md
- scissors/my_random.sh
- scissors/rock-paper-scissors.sh
> Vitaliy.zhyrko

- 03_module/Makefile
- 03_module/dump.txt
- 03_module/hello.c
The module accepts two integer parameters n1 and n2 and provides:
- A sum of parameters upon the module load
- A substration of parameters upon the module unload
Signed-off-by: Ivan Stepanenko <istepanenko@gmail.com>
> Task03: Implement basic module with params.

- 01_git/Makefile
- 01_git/main.c
Rock-paper-scissors game.
To play the game enter your sign: r - for "Rock", p - for "Paper", s - for "Scissors".
Press Ctrl+D or Ctrl+Z to exit the game
> TASK1: rock-paper-scissors game

- 02_bash/hwdetect/hwdetect.sh
Implement hwdetect script, which detects for new devices, like SD cards, USB to TTL, i2c, flashes
> TASK02: Implement hwdetect

- 01_git/makefile
- 01_git/scissors.c
- 01_git/scissors.h
- 02_bash/hwdetect.sh
- 03_module/Makefile
- 03_module/dump.txt
- 03_module/prmmod.c
- 04_basic_struct/Makefile
- 04_basic_struct/dump.txt
- 04_basic_struct/recv_msg.c
> Volodymyr.kniazkyi

- 02_bash/hwdetect/hwdetect.sh
Signed-off-by: kun <Kurylko.n@gmail.com>
> TASK2: Add solution for hwdedect script

- 03_module/Makefile
- 03_module/argsmod.c
- 03_module/compilation_log.txt
- 03_module/console_log.txt
- 03_module/dmesg_log.txt
This PR supersedes "TASK3: Implement a basic module with params. #69" which had several unwanted commits due to a mistake with syncing from origin/main (branch  Kernel-GL-HRK /gl_kernel_procamp_2021/ Victor.Krasnoshchok wasn't synced from main before opening a PR and that led to appearing of several "extra" commits among my own ones).
Fixed by https://github.com/Kernel-GL-HRK/gl_kernel_procamp_2021/pull/70 (just sync from Kernel-GL-HRK/gl_kernel_procamp_2021/main , no course-related commits which needed approving).
> TASK3: Implement a basic module with params.

- 01_git/scissors/Makefile
- 01_git/scissors/rpscissors.c
Initial version of rock-paper-scissors game with md5
Signed-off-by: kun <Kurylko.n@gmail.com>
> TASK1: Add solution

- 05_timers/App/get_time.c
- 05_timers/App/makefile
- 05_timers/Module/Makefile
- 05_timers/Module/clc_time.c
- 05_timers/Module/dump.txt
Implement program which return absolute time in user space.
Implement kernel module wich return relative and absolute
time since previous read of it.
> 05_timers: Add homework for Linux Kernel Time Management lesson

- 03_module/Makefile
- 03_module/kernel.log
- 03_module/kmodule.c
Signed-off-by: Nazarii Kurylko <kurylko.n@gmail.com>
> TASK3:Implement solution for the TASK3

- 04_basic_struct/Makefile
- 04_basic_struct/myobject.c
Signed-off-by: Nazarii Kurylko <kurylko.n@gmail.com>
> TASK4: Implement kobject with linked list

- 06_memory/App/dump.txt
- 06_memory/App/makefile
- 06_memory/App/memory_tst.c
- 06_memory/Module/dump.txt
- 06_memory/Module/makefile
- 06_memory/Module/memory_tst_mod.c
Create user-space program and test allcation/freeing time for
functions malloc, calloc and alloca.
Create kernel module and test allocation/freeing time for
functions kmalloc, kzalloc, vmalloc, and get_free_pages.
> 06_memory: Add homework for Memory management lesson

- 05_timers/kernel_module/Makefile
- 05_timers/kernel_module/dump.txt
- 05_timers/kernel_module/time_attr_presenter.c
- 05_timers/user_space/Makefile
- 05_timers/user_space/dump1.txt
- 05_timers/user_space/user_space_timers.c
Task05: Implement program which return abs time in user space and kernel module that shows abs&relat time since last read.
> 05 timers task

- 04_basic_struct/README.md
- 04_basic_struct/module_bstruct/Makefile
- 04_basic_struct/module_bstruct/log.txt
- 04_basic_struct/module_bstruct/module_bstruct.c
Task4: Implemented basic module with linux kernel linked list data structure
> Task4: Implemented basic module with linux kernel linked list data structure

- 01_git/scissors/main.c
- 01_git/scissors/makefile
- 02_bash/hwdetect/hwdetect.sh
- 03_module/TASK3/Makefile
- 03_module/TASK3/TASK3.c
- 03_module/TASK3/kernel_log.txt
- 04_basic_struct/TASK4/Makefile
- 04_basic_struct/TASK4/TASK4.c
- 04_basic_struct/TASK4/log.txt
> vadym.hutovskyi

- 03_module/README.md
- 04_basic_struct/README.md
- 04_basic_struct/module/Makefile
- 04_basic_struct/module/my_module.c
- 04_basic_struct/module/usage_log.txt
On read form attribute "list" it shows content of the objects linked list.
On write to attribute "list" it add new string to the objects linked list.
> Task04: Add basic struct driver

- 05_timers/Kernel/Makefile
- 05_timers/Kernel/kernel_space.c
- 05_timers/Kernel/log.txt
- 05_timers/User/Makefile
- 05_timers/User/log.txt
- 05_timers/User/user_space.c
Signed-off-by: Vadym.Hutovskyi <vadym.hutovskyi@globallogic.com>
> TASK5: ready for review

- 03_module/module/Makefile
- 03_module/module/hello_module.c
- 03_module/module/kernel.log
> TASK03: Add simple kernel module

- 07_procfs/Makefile
- 07_procfs/orangepi_dump.txt
- 07_procfs/procfs_mod.c
Create kernel module with procfs API
Build image for orange pi zero
Run this module on orange pi zero board
> 07_procfs: Add homework for ProcFS and platform bootup lesson

- 03_module/simple_module/Makefile
- 03_module/simple_module/dump.log
- 03_module/simple_module/smodule.c
Implemented simple module with source file, Makefile and log dump.
> TASK03: Implement simple module

- 08_irq_handling/led_irq/Makefile
- 08_irq_handling/led_irq/ledirq_mod.c
- 08_irq_handling/led_pool/Makefile
- 08_irq_handling/led_pool/ledpool_mod.c
Modify and run polling example module on Orange Pi board
Create driver with irq handling instead of pooling mechanism
> 08_irq_handling: Add homework for IRQ-handling lesson

- 08_irq_handling/led_mod.c
Signed-off-by: Nazarii Kurylko <kurylko.n@gmail.com>
> TASK08: Implement irq handling of button gpio instead of pooling

- 01_git/README.md
- 02_bash/README.md
- 07_procfs/module/Makefile
- 07_procfs/module/my_module.c
- 07_procfs/module/usage_log.txt
- README.md
Creates three files in /proc/my_module folder:
File 'author' returns a module author name.
File 'store_count' returns number of "store" sysfs attribute calls.
File 'show_count' returns number of "show" sysfs attribute calls.
> Task07: Add ProcFS interface to the existing module.

- 10_chardev/Makefile
- 10_chardev/chardev_mod.c
- 10_chardev/ioctl_common.h
- 10_chardev/logs.txt
- 10_chardev/user_app.c
… to control status led and user led
> Task10: Implemented character device driver and userspace application

- 10_chardev/Makefile
- 10_chardev/dev.h
- 10_chardev/index.html
- 10_chardev/ioctl_app.c
- 10_chardev/ioctl_mod.c
- 10_chardev/server.c
Create character device driver to control status led and user button
Create user space application to control status led and user button
Modify and run simple web-server to control status led
> 10_chardev: Add homework for character devices lesson

- 01_git/scissors/Makefile
- 01_git/scissors/RockPaperScissors.c
Destination branch changed to ViacheslavHolubnychyi.
Detailed descriptions added to commits.
Makefile to build binary file added.
> Task01: Rock-Paper-Scissors game
